### ISSUE TITLE
Redesign the app

### ISSUE THREAD

**Issue by brafdlog** [brafdlog/caspion#102]
After we have a working MVP it would be a good time to stop and think what we want the UI/UX of the app to be.

Take into account:

- Configuring importers
  - YNAB setup
  - Google sheets setup
- Configuring exporters
- Global configuration (like show browser)
- Import and export progress indication
- Category management  and rules for automatically assigning transactions to categories
- Report after imporn export finishes

**Comment by baruchiro** [comment]
@brafdlog There are no action items here, I think it can be close. See #143
