### ISSUE TITLE
Improve error handling and event emitting in case of error

### ISSUE THREAD

**Issue by brafdlog** [brafdlog/caspion#105]
Currently every error during the import or export process makes the whole process fail. In addition, there are cases where multiple error events will be emitted for the same error.
We need to decide on a consistent way to handle errors. Probably don't want to crash the whole process because one importer or exporter fail but we do want to indicate the failure clearly to the user

**Comment by baruchiro** [comment]
I think the type of the `scrapeAndUpdateOutputVendors` return value is also related to this issue, because this type is actually a map from *Exporter Name* to *Exporter Results*, and after you organize the internal flow, you can define a unified result type.

**Comment by brafdlog** [comment]
This has been improved since
