### ISSUE TITLE
Implement an update flow for the app (see auto-update)

### ISSUE THREAD

**Issue by Moshet** [brafdlog/caspion#114]
Syncing with the main Israeli Bank Scrapers project updates will provide a better experience for the user and eliminate the need to update the software manually.

**Comment by baruchiro** [comment]
I don't know how to implement that, but another option is to alert the user that there is an update to the software.

**Comment by brafdlog** [comment]
Syncing with the Israeli bank scrapers prohject means updating the version of their library.
So what I understand from what you say is that you would like to see an easy update flow. Is that what you mean?

**Comment by brafdlog** [comment]
Updating the israeli-bank-scrapers versions requires updating the code. So I changed this to a more generic issue of implementing the flow of updating the app.

This also relates to #125

**Comment by baruchiro** [comment]
Please think about "multi-branch" upgrades.

Imagine a user that wants to check the update before he installing it (I think in our app, that accessing the bank passwords, can be happened).
Maybe the user doesn't want new features until he validates them, but meantime, if the `israeli-bank-scrapers` have changed, we want to push their change quickly, even without other features.

**Comment by baruchiro** [comment]
Closing, it already implemented
