### ISSUE TITLE
Add an icon for opening each exporter results

### ISSUE THREAD

**Issue by brafdlog** [brafdlog/caspion#137]
For each type of exporter, add an icon that when clicked will open the relevant exporter

- Csv and json will open the file
- Ynab will open the ynab website in the correct url in the default browser
- Sheets will open the google sheet we are exporting to in the default browser

**Comment by baruchiro** [comment]
Good idea!

**Comment by baaraak** [comment]
Sure, no problem...
We are talking about this screen right?:
![Untitled](https://user-images.githubusercontent.com/16448454/121670793-81794880-cab6-11eb-9e05-1e582846c367.png)
I will take a look later and let you know if I have any question about how should I implement it

**Comment by ErezBiren** [comment]
I can take it.

**Comment by ErezBiren** [comment]
Fixed in #445

**Comment by baruchiro** [comment]
@ErezBiren Tried it now.

First, it is working even if an exporter is disabled, I don't know if it is the wanted behavior.

Second, nothing happened when clicking on the `JSON` exporter.

**Comment by ErezBiren** [comment]
1. @baruchiro @brafdlog 
would you like the open result button to be hidden or disabled when the exporter is disabled?

2. The JSON exporter results seem to work fine for me.
Did you check that the file path is correct?

**Comment by brafdlog** [comment]
1 makes sense to me
Havent tried the json yet, can try later

**Comment by ErezBiren** [comment]
Ok, but to hide or should we disable the button?

**Comment by brafdlog** [comment]
Hide
