### ISSUE TITLE
Choose a name for the app and update the code

### ISSUE THREAD

**Issue by brafdlog** [brafdlog/caspion#140]
Choose a name for the app and update the code to that name.

Related discussion #139

**Comment by baruchiro** [comment]
I think the real work is by #103 

@brafdlog I suggest changing the repo name. Don't worry, Github will redirect the old URL to the new one for a time.

**Comment by baruchiro** [comment]
Also, of course, the repo path in the `package.json` should be updated.

**Comment by MordRot** [comment]
And app name in: `globals.js`

**Comment by baruchiro** [comment]
@brafdlog Please change the repo name.
Don't worry, it will redirect the current URL to the new one for some time. (AFAIK)

**Comment by baruchiro** [comment]
Reopen: rename to כספיון
https://github.com/brafdlog/hiuvi/discussions/139#discussioncomment-885000
