### ISSUE TITLE
Create a landing page for the app

### ISSUE THREAD

**Issue by brafdlog** [brafdlog/caspion#146]
Create a landing page with a basic explanation and a link to download the app

**Comment by baruchiro** [comment]
Please take a look at the `nuxt` folder, with the old landing page- https://baruchiro.github.io/israeli-bank-scrapers-desktop/

**Comment by baruchiro** [comment]
I collected some FAQ to share with the users:

 - למה לא רואים פירוט אשראי?  
   פירוט אשראי מגיע מאתר האשראי, ופירוט העובר ושב מגיע מאתר הבנק. לא ניתן לקבל נתוני פירוט אשראי ע"י פרטי הכניסה לאתר הבנק.
 - כמה זמן אמור לקחת לייבוא הנתונים?  
 לא הרבה (צריך למדוד). במידה והסיסמה שגויה דווקא ייקח לו מעט יותר זמן לגלות זאת. בכל מקרה במידה ויש בעיה מומלץ לסמן את הכפתור של הצגת הדפדפן ולבדוק באיזה שלב בגלישה יש בעיה.
 - לחצתי על "ייבוא" ולא קרה כלום?  
  אם זאת הפעם הראשונה שלך, כנראה שהתוכנה מורידה את הדפדפן כרום, וזה יכול לקחת זמן, תלוי במהירות הגלישה.

From https://github.com/baruchiro/israeli-bank-scrapers-desktop/issues/27

**Comment by baruchiro** [comment]
How it works?
Explain about scraping, israeli-bank-scrapers etc

**Comment by baruchiro** [comment]
Explain about the passwords and the risk
