### ISSUE TITLE
Orgnize exports from Backend

### ISSUE THREAD

**Issue by baruchiro** [brafdlog/caspion#194]
- [ ] The `backend/index.ts` should include (in my opinion) only `import`s and `export`s, without function implementation.
- [ ] With that, I think also we need to export short list of objects, with all the methods with them (for example, export `Config` with `Config.loadConfig` and `Config.saveConfig`.

https://github.com/brafdlog/budget-tracking/blob/fc70a7bc08d6f711ac3d59fac213ec064df07529/src/backend/index.ts#L20-L48

**Comment by itayweb** [comment]
Hey, I think I can take that on me but can you explain more about the second part? The first part I think I understood but the second part I didn't understand what did you meant

**Comment by baruchiro** [comment]
Hi @itayweb, I don't know how much experience you have, but this issue is about refactoring the whole structure of the code.

It requires experience of working with complex systems before, and I can't list all the actions it may takes.

Thank you.

**Comment by itayweb** [comment]
@baruchiro I thought it's only to split the `index.js` to smaller files, if it's more than that I'll take a look into other issues :)

**Comment by baruchiro** [comment]
Please search for other issues, thanks :-)

If you need any help you're welcome to contact us on Discord: https://discord.gg/cVd7V6D2
