### ISSUE TITLE
Invalid Opening Quote: a quote is found inside a field at line 1

### ISSUE THREAD

**Issue by baruchiro** [brafdlog/caspion#262]
From user:

![image](https://user-images.githubusercontent.com/17686879/122248214-9ac42f80-ced0-11eb-81f9-e104d0d63c36.png)

<p dir='rtl' align='right'>
"הוא פותח כרום, עושה login, נשאר שם שניה, עובר למזרחי באנגלית לדף לא קשור ונותן שגיאה."
</p>

**Comment by baruchiro** [comment]
From a quick search, it seems like a problem with export to CSV.

**Comment by brafdlog** [comment]
I tried running the scraper with mizrachi and csv export and could not reproduce.

@baruchiro Do we have any other input? If not I think we can close

**Comment by baruchiro** [comment]
I'm chatting with the user on FB, but we can't understand the problem.

I think we can keep it open for a while.

**Comment by baruchiro** [comment]
Closed: Not reproduced.
