### ISSUE TITLE
היוש!

### ISSUE THREAD

**Issue by sapir1472** [brafdlog/caspion#263]
מופיע לי שגיאה בכניסה לאתר לאומי ולמקס
מצרפת פרטים של השגיאה
![image](https://user-images.githubusercontent.com/63669066/122269294-b6860080-cee5-11eb-9519-39069fe80740.png)

![image](https://user-images.githubusercontent.com/63669066/122269327-c1d92c00-cee5-11eb-9064-7fb783ad3030.png)

כשעשיתי הצגה דרך הדפדפן, אז ראיתי מה הבעיה בדיוק (זה ממלא פרטים לא במקום הנכון, או לא לוחץ על כפתור הכניסה אחרי שמילא פרטים), אז הספקתי "לעזור" לתוכנה להתחבר לאתר לאומי, אבל לאתר של מקס יש כמה שלבים וזה לוקח יותר מדי זמן עד שהחלון נסגר.

**Comment by baruchiro** [comment]
<div dir="rtl">
היי, תראי, קודם כל, המשיכה עצמה מתבצעת על ידי פרויקט אחר שאחראי נטו על משיכת הנתונים, וגם הוא דורש תחזוקה מהקהילה, כי לא לכולם יש חשבונות בנק באותו מקום ;-)

בכל מקרה, הבעיות האלו נראות כמו בעיות של אינטרנט איטי. יש מצב שאת גולשת מהפלאפון או משהו?
</div>

**Comment by sapir1472** [comment]
היי!
קודם כל חשוב לי להגיד אם זה לא היה ברור, שאני לא באה בטענות או ביקורת.
קראתי את הפוסט שלכם אתמול בסופרטולז וברור לי שאתם משקיעים בזה מזמנכם החופשי.
שלחתי את הנ"ל כי לא ראיתי שדיווחו על הבאגים האלה בשרשור באותו פוסט (בניגוד
לפועלים שכן היה שם).

אני גולשת מהמחשב, אבל ייתכן מאוד ואלו בעיות של מהירות אינטרנט. אני אנסה שוב
או ממקום אחר ואם זה יחזור על עצמו אעדכן.

שוב תודה על הכל :)

‫בתאריך יום ה׳, 17 ביוני 2021 ב-7:50 מאת ‪Baruch Odem (Rothkoff)‬‏ <‪
***@***.***‬‏>:‬

**Comment by baruchiro** [comment]
הכל טוב, זה פשוט הסבר שאני מסביר לכולם בגלל שזה הולך לקרות הרבה. המנוע הזה לא יציב, אין מה לעשות, והרבה תלונות עליו יצטרכו לעבור הלאה

**Comment by brafdlog** [comment]
אין לי חשבון מקס אם לאומי אז קצת מורכב לבדוק את זה.

האם זה עדיין משתחזר?

**Comment by baruchiro** [comment]
אצלי לא

**Comment by brafdlog** [comment]
בדקתי מאז את מקס ואצלי זה עבד. אני סוגר את זה ואם זה עדיין משתחזר מוזמנת לפתוח מחדש
