### ISSUE TITLE
[SECURITY] Credentials are passed to a 3rd party library

### ISSUE THREAD

**Issue by zavelevsky** [brafdlog/caspion#264]
Code in question is [here](https://github.com/brafdlog/hiuvi/blob/e47a54ac4a125342398f1b62c195efa6c7c29835/src/backend/import/bankScraper.ts#L45):

The gist: there's a security weakness in passing the user's bank credentials over to a 3rd party code library.
This weakness should be fixed - and in the meantime it should be made clear to the users in the README.

Details:
User credentials are passed to israeli-bank-scrapers-core. This library uses Puppeteer to launch Chrome and drive it to the relevant bank website, where it enters the credentials automatically to in the login form and then has full access to the bank account.
What this library POTENTIALLY could do is:
 - call an external server and leak the credentials and bank details over to it. 
 - navigate the headless chrome over to another website and submit the credentials, and only then move on to the bank site.
 - (more evasive) save the credentials locally so that another library will be able to find this file and leak it.
 - more ?

We can't tell for sure if the library does it or not because we are using their bundled and published npm package and not their source code that's published on Github.

Suggested fix: bundle the source code yourself after reviewing it carefully.
Alternatively, we can launch chrome and puppeteer ourselves, pass the login challenge and then pass the open session to the library so that they'll do the data extraction (it will involve their cooperation).

**Comment by baruchiro** [comment]
You're right, all those attach vectors are about someone who will change the code/package in `israeli-bank-scrapers`.

I think it can be solved in a more simple way. We need to create a checklist like that:

1. Review the change between the versions.
2. Make sure the current version in npm released by the [Github Action](https://github.com/eshaham/israeli-bank-scrapers/runs/2739732884?check_suite_focus=true) and not manually.

Is it enough?

**Comment by zavelevsky** [comment]
It's a step forward, indeed.
I don't think it solves the entire issue because, if you consider things from the end user's perspective, then she has no guarantee that reflects in your code - what you offer is a manual practice that takes place in the process of updating dependencies.
In my opinion the best solution will be to use the scrapers library in a way that doesn't provide them with actual access to credentials and bank account - but this requires the library maintainers to provide such an API. I suggested it to them in this [Facebook discussion](https://www.facebook.com/groups/supertool/permalink/969436120458794/) (Hebrew)
![image](https://user-images.githubusercontent.com/672016/122660703-e9512280-d18b-11eb-8cfa-1ec529063609.png)
![image](https://user-images.githubusercontent.com/672016/122660707-f4a44e00-d18b-11eb-95e5-01033767c4a0.png)

**Comment by brafdlog** [comment]
This is a valid concern. There is a level of risk/trust in the current implementation that could be mitigated. Note that this trust issue still exists even if we implement the suggested solutions - it just moves from trusting israeli-bank-scrapers to trusting Baruch and myself. We could theoretically have the same bad intentions.
Our short term goal is to get the app out to users so we provide this value for people who need it and get feedback. This version is out with multiple caveats, not least among them is that the security is far from perfect.
While this is a concern, we do want to give people the ability to decide if they are early adopters and are willing to use it at the current stage or they want to wait. Hence the disclaimer: https://github.com/brafdlog/hiuvi#disclaimer

Longer term, there could be a few options of how to mitigate. In addition to your suggestions, we could also allow a mode where the scraper waits for the user to put the credentials himself manually, thus having no need to save them at all.

We can keep this discussion alive for the longer term solution, but as we wrote, our short term focus will not be on this.

**Comment by zavelevsky** [comment]
As you can see, I've opened an issue in hope that the israeli-bank-scrapers project will address this https://github.com/eshaham/israeli-bank-scrapers/issues/588
