### ISSUE TITLE
Exported .csv is not saved as utf-8 encoding - Hebrew characters are shown as gibberish

### ISSUE THREAD

**Issue by sagilo** [brafdlog/caspion#265]
The csv file should be saved as UTF-8 otherwise Excel and other encoding sensitive applications may show gibberish instead of Henrew characters
See example:
![image](https://user-images.githubusercontent.com/5019344/122420719-8ea1a600-cf94-11eb-85a8-3e94ecb9d52b.png)

**Comment by baruchiro** [comment]
Yes you're right. Meantime I remembered this and that for now you need to "import" the CSV to Excel using Excel Data tools.

Thank for your issue.

**Comment by brafdlog** [comment]
Stange. I checked, and the code that writes the file encodes with utf-8 (the default encoding for `fs.writeFile`.
Also when opening the file in notepad I see the Hebrew characters.
So this seems like an issue with excel opening csvs with unicode characters.

**Comment by baruchiro** [comment]
The solution for this issue should be to solve the problem or write an explanation.

**Comment by baruchiro** [comment]
Closed by #273
