### ISSUE TITLE
Google Sheets enabled even if not connected to Google

### ISSUE THREAD

**Issue by baruchiro** [brafdlog/caspion#284]
If I left the application with Google Sheets enabled, and I opened it after a long time, I needed to re-authenticate with Google. I didn't do it, but still, the Google Sheets was enabled as exporter (and of course, it failed).

![image](https://user-images.githubusercontent.com/17686879/134357664-5d656818-3f87-400f-8beb-3a284370f902.png)

**Comment by fabform** [comment]
Handy to [find google sheet id](https://fabform.io/a/how-to-find-google-sheet-id)
