### ISSUE TITLE
Issue with Visa Cal integration

### ISSUE THREAD

**Issue by RoiSec** [brafdlog/caspion#287]
Hi,
When I execute the integration with Visa CAL, I got two types of errors:

1. "invalid json response body at https://cal4u.cal-online.co.il/Cal4U/CardsByAccounts reason: Unexpected end of JSON input"

2. "unknown transaction type null"

When I repeat the action I see that "login success" and then I got the second error...

**Comment by baruchiro** [comment]
It is a known bug, see #282. We are waiting for https://github.com/eshaham/israeli-bank-scrapers/issues/602 to be closed.

**Comment by brafdlog** [comment]
Closing as duplicate. See #282
