### ISSUE TITLE
Increase the period of feach from Isracard

### ISSUE THREAD

**Issue by RoiSec** [brafdlog/caspion#289]
Hi,
Isracard's integration has a limit of - fetch of payment data only for the last year.
Is it possible that it will be for longer? Maybe have an issue with caspion that does not provide correct data to the scraper?

Thanks

**Comment by baruchiro** [comment]
Most of the scrapers in [`israeli-bank-scrapers`](https://github.com/eshaham/israeli-bank-scrapers) limit their fetch to one year. You can see the Isracard code here:

https://github.com/eshaham/israeli-bank-scrapers/blob/7c6bc3e8e277ff123219b56ae3dcbfa822fffdd8/src/scrapers/base-isracard-amex.ts#L353-L355

First, check how long you can see your transactions on the Isracard website. If it's more than one year, we can open an issue, and maybe a PR, to fix it in `israeli-bank-scrapers`.

**Comment by RoiSec** [comment]
Yes, I have already changed the code for 3 years and it works.
But how are you cause Caspion to update this?

**Comment by baruchiro** [comment]
We will merge the #285 and a new version will be available.
