### ISSUE TITLE
Scraping stuck on loading when multiple importers of the same type are defined

### ISSUE THREAD

**Issue by brafdlog** [brafdlog/caspion#308]
@Rea reported this.
Scenario:
Defined two visal cal importers and two isracard importers.
When scraping, one visa cal and one isracard stay stuck on in progress state
![image](https://user-images.githubusercontent.com/7272927/147650033-be643147-f8f9-4ec9-a254-24cddd399537.png)

**Comment by ReaBar** [comment]
you mentioned the wrong rea ;)

**Comment by baruchiro** [comment]
> @brafdlog you mentioned the wrong rea ;) I rechecked and you can close this issue, the issue was password out of date. the UI is with the sand clock is confusing.

I still think there is a bug here. Usually, if there is an error, `CHANGE_PASSWORD` or `GENERIC`, it should display an error icon, don't remember how it looks like...

**Comment by brafdlog** [comment]
Closing unless we get validation in react UI that this is still an issue
