### ISSUE TITLE
Hapoalim Error Evaluation failed: TypeError: Failed to fetch

### ISSUE THREAD

**Issue by idanco1** [brafdlog/caspion#309]
Hi

I get an error from Poalim importer
![image](https://user-images.githubusercontent.com/72490001/148806078-cbbf6e49-c82a-4e10-ad36-b1d73a5fac2e.png)

Thanks

**Comment by idanco1** [comment]
Seems like Israeli Bank Scraper release a fix for that on 30/12
https://github.com/eshaham/israeli-bank-scrapers/issues/640

Is there a way to release a new version of Caspion that will use that latest israeli bank scrapers version ?

**Comment by brafdlog** [comment]
Created a PR for this, once this is merge will create a new release

**Comment by brafdlog** [comment]
@idanco1 try updating to `v0.0.13-beta`

**Comment by idanco1** [comment]
Thank you
@brafdlog 

Where do i find the exe setup file ?

**Comment by baruchiro** [comment]
@idanco1 You can update from your current installation, in the bottom left corner.
Also, you can download the latest version from our website: https://brafdlog.github.io/caspion/ (@brafdlog please add this URL to the repository "About" section")

And you can find the release here: https://github.com/brafdlog/caspion/releases/latest

**Comment by idanco1** [comment]
@baruchiro 
Thanks
I might be missing something , but https://github.com/brafdlog/caspion/releases/latest does not include exe files like previous versions
and update from Caspion returns "error during update"

**Comment by baruchiro** [comment]
Yes, we didn't publish the latest version correctly, I'm fixing it right now.

I have a plan to automate this process: #297

**Comment by baruchiro** [comment]
@idanco1 Try now please

**Comment by idanco1** [comment]
Thanks ! @baruchiro 
All working now
