### ISSUE TITLE
Error import visa cal transaction

### ISSUE THREAD

**Issue by RoiNsec** [brafdlog/caspion#335]
Hi 
I got every time timeout error . 
"Navigation timeout of 30000 ms exceeded"
The issue was solved ,
The error occurs because I need to change the password.

**Comment by baruchiro** [comment]
Hi, so now everything is working well?

**Comment by RoiNsec** [comment]
Yes,
It would be nice for the app to throw in an error that needs a password change

**Comment by baruchiro** [comment]
It should throw such, but possibly the website was changed and you need to contribute some code to update the scraper:

https://github.com/eshaham/israeli-bank-scrapers/blob/347d9b58974a71c256313552389914afc1bf5d8e/src/scrapers/visa-cal.ts#L78
