### ISSUE TITLE
issue with FIBI importer

### ISSUE THREAD

**Issue by agammyshhay** [brafdlog/caspion#351]
hi,

import from FIBI doesnt work. this is the error message i get:
"waiting for selector `#matafLogoutLink` failed: timeout 30000ms exceeded"

i have no technical background, i will be very happy to help solve it, if someone will guide me

thanks !

**Comment by baruchiro** [comment]
Hi, what is "FIBI"?

**Comment by agammyshhay** [comment]
Hi,

sorry, its 'First International Bank Israel' - "habenleumi"

**Comment by baruchiro** [comment]
I will first update Caspion with the new updates from `israeli-bank-scrapers`, then you'll check again.

**Comment by agammyshhay** [comment]
Thanks a lot
let me know if i can help somehow

‫בתאריך יום ה׳, 16 ביוני 2022 ב-8:10 מאת ‪Baruch Odem (Rothkoff)‬‏ <‪
***@***.***‬‏>:‬

**Comment by baruchiro** [comment]
Please check the new version now: https://github.com/brafdlog/caspion/releases/tag/v0.0.20-beta

**Comment by agammyshhay** [comment]
Thanks

it didnt solve the problem, and it create a new problem in Visa Cal import:
[image: image.png]
its stuck like that all the time since i upgrade, and the whole import
process stuck with it:
[image: image.png]

‫בתאריך יום ו׳, 17 ביוני 2022 ב-10:38 מאת ‪Baruch Odem (Rothkoff)‬‏ <‪
***@***.***‬‏>:‬

**Comment by baruchiro** [comment]
I can't see the screenshots, please comment from the Github interface :-)

**Comment by agammyshhay** [comment]
Hi

its seems like the VIsa bug is gone  - so it doesnt mind (maybe it was temporary from Visa side), but the BENLEUMI bug is still here

Thank alot

**Comment by baruchiro** [comment]
Issues during the scraping process are related to the `israeli-bank-scrapers` project, here is your issue there: https://github.com/eshaham/israeli-bank-scrapers/issues/691
