### ISSUE TITLE
bug - import stuck on "Terminating" 

### ISSUE THREAD

**Issue by agammyshhay** [brafdlog/caspion#354]
Hi,

the import is stuck on "Terminating" and never move forward to "importer end"  - it happened a lot in Visa import - sometime everything is fine, but then it reoccur - today its like this since 07:00AM for 6-7 retries.

Thanks

![image](https://user-images.githubusercontent.com/107346921/174567126-a56dbb61-ceac-4d5b-b33a-e73b0c0dc900.png)

**Comment by baruchiro** [comment]
Thanks for reporting, I think it was also reported here by @agammyshhay: https://github.com/brafdlog/caspion/issues/351#issuecomment-1158811113.

Usually, errors in the import process are related and reported to the [`israeli-bank-scrapers`](https://github.com/eshaham/israeli-bank-scrapers) project. Still, here I'm not sure and we need to check if it is related to the library, or to Pupetter itself, maybe it couldn't kill the process.

Do you have any technical skills that will help us research this issue?

**Comment by agammyshhay** [comment]
it was me :-) (i thought it was temporary bug, but now i see its happened alot
unfortunately i dont have technical skills....

**Comment by brafdlog** [comment]
@agammyshhay  is this still happening? If so we will need some more data to reproduce. Feel free to reopen
