### ISSUE TITLE
Question: is there anyway to automate Caspion to run every day?

### ISSUE THREAD

**Issue by agammyshhay** [brafdlog/caspion#355]

**Comment by agammyshhay** [comment]
sorry if its not the place to ask it
i am new to this kind of stuff

**Comment by baruchiro** [comment]
You're welcome to join our [discort channel](https://discord.com/channels/924617301209260103/924617301209260106), I just answered there.

Currently, there is no way to run it automatically. We should implement a CLI to make it happen: #183, and we need help with that.
