### ISSUE TITLE
upgrading to israeli-scrapers v1.14.3

### ISSUE THREAD

**Issue by orentet** [brafdlog/caspion#359]
Hello.
There is a problem in cal, which was fixed in the latest version.

when are you planning to create a new version, and upgrade to this? as cal is currently not working.

**Comment by brafdlog** [comment]
This version is already in master. Try the latest.
Visa cal worked for me after fix

**Comment by orentet** [comment]
I mean an actual packaged version, not downloading source from master

3 Jul 2022 22:06:23 Jonathan ***@***.***>:

**Comment by brafdlog** [comment]
I see what you mean, i didnt create a new production release.
Can you try the latest beta release (0.0.21-beta) from the releases page?
Verify that it works for you and then I will create an official release

**Comment by baruchiro** [comment]
I will create a release after #360 #361
