### ISSUE TITLE
Import works only with one account

### ISSUE THREAD

**Issue by changecompassthe** [brafdlog/caspion#363]
But what to do if you have more than 1 one account in one bank?

**Comment by baruchiro** [comment]
What error did you get?

I see someone opened similar issue before, but it was by mistake: https://github.com/brafdlog/caspion/issues/308

**Comment by brafdlog** [comment]
@changecompassthe does this work in the new UI? Please try the latest release and tell me if it works for you.
Closing for now, feel free to reopen if reproduces
