### ISSUE TITLE
Google Chrome block download

### ISSUE THREAD

**Issue by sk3pp3r** [brafdlog/caspion#370]
![image](https://user-images.githubusercontent.com/15815967/188614932-f50124f8-d664-4ece-871d-7d8c93367050.png)

Google Chrome block download

**Comment by baruchiro** [comment]
You should click on the arrow and select "keep".

https://www.addictivetips.com/web/fix-this-file-is-not-commonly-downloaded-and-may-be-dangerous-error-in-chrome/#:~:text=fix%20%E2%80%98file%20is%20not%20commonly%20downloaded%20and%20may%20be%20dangerous%E2%80%99

**Comment by baruchiro** [comment]
@sk3pp3r You are welcome to join our discord channel: https://discord.gg/XWWg7xvJyS
