### ISSUE TITLE
Export to ofx

### ISSUE THREAD

**Issue by mbrevda** [brafdlog/caspion#381]
Would be great to see the ability to export to `.ofx`. This would help unlock the majority of financial applications and make using them with Israeli banks much simpler. Thanks!

**Comment by baruchiro** [comment]
Thanks! Can you explain more about `ofx`?

**Comment by mbrevda** [comment]
It's a common format that desktop apps & banks use. For example, Quicken can automatically download data from most US banks. But if your bank isn't supported by they offer ofx exports, you can import the data to Quicken.

**Comment by baruchiro** [comment]
@mbrevda I see you're a JS developer, do you want to implement it here?

**Comment by ErezBiren** [comment]
I can take it.

**Comment by mbrevda** [comment]
@ErezBiren did you ever get anywhere with this?
