### ISSUE TITLE
Overlapping controls

### ISSUE THREAD

**Issue by ShiranAbir** [brafdlog/caspion#401]
When adding multiple card providers, the controls and text can overlap the cards as shown below:
![Screenshot_20221130_125923](https://user-images.githubusercontent.com/106183696/204883274-cd0d6bf3-80a0-4c8e-9ef9-4884496978ba.png)

**Comment by ShiranAbir** [comment]
While I was trying a fix, I learned that the controls are `React-Bootstrap` controls.
Searching the affected `Stack` controller, it seems that the previous gap ({5}) is the biggest builtin-gap possible:
https://react-bootstrap.github.io/layout/stack/#:~:text=Sets%20the%20spacing%20between%20each%20item.%20Valid%20values%20are%200%2D5.

This required me to creat a custom gap CSS class which will have adequate gap for the controls has seen below:
![Screenshot_20221130_125942](https://user-images.githubusercontent.com/106183696/204884195-d47f2b68-936a-433f-bc9b-0ae1b6b0b8c7.png)

**Comment by baruchiro** [comment]
> While I was trying a fix, I learned that the controls are `React-Bootstrap` controls. Searching the affected `Stack` controller, it seems that the previous gap ({5}) is the biggest builtin-gap possible: https://react-bootstrap.github.io/layout/stack/#:~:text=Sets%20the%20spacing%20between%20each%20item.%20Valid%20values%20are%200%2D5.
> 
> This required me to creat a custom gap CSS class which will have adequate gap for the controls has seen below: ![Screenshot_20221130_125942](https://user-images.githubusercontent.com/106183696/204884195-d47f2b68-936a-433f-bc9b-0ae1b6b0b8c7.png)

Hi @ShiranAbir, I think next time, a comment about doubt in the final implementation should be in the PR and not in the issue.

Thank you!!!
