### ISSUE TITLE
Complete React migration

### ISSUE THREAD

**Issue by baruchiro** [brafdlog/caspion#404]
From #294:

- [x] Unify react wip flow into repo
- [x] Linting errors
- [x] Allow running react version side by side with vue version to allow merging before full feature parity
- [ ] Implement all flows
  - [x] Importers create/update/delete
  - [x] Importers enable/disable
  - [ ] Exporter settings
    - [x] Excel
    - [x] JSON
    - [x] Ynab
    - [ ] Google sheets - #427 
  - [x] General settings (num scraping days and show browser)
- [x] Improve error indications in ynab exporter edit

Maybe in a separate PR:
- [ ] Improve UX to match design
- [ ] Improve logging to show full message including error
- [x] Solve ynab api issue and remove disabling of https check
- [x] Error reporting (sentry)
- [ ] Analytics
- [ ] Download Chrome progress
- [ ] Remove vue #428 
  - [ ] Switch to [electron-react-boilerplate](https://github.com/electron-react-boilerplate/electron-react-boilerplate)? 
  - [ ] Replace electron builder vue
  - [ ] Remove view files and build
- [ ] Check for updates flow #429 
- [ ] Monorepo
  - [ ] Separate to worskpaces (yarn workspaces? [with lerna](https://medium.com/@jsilvax/a-workflow-guide-for-lerna-with-yarn-workspaces-60f97481149d))?
  - [ ] Solve react dependency issue and remove SKIP_PREFLIGHT_CHECK hack

**Comment by ErezBiren** [comment]
@baruchiro 
I think that "Error reporting (sentry)" can be checked.

**Comment by brafdlog** [comment]
Created seperate issues for the main remaining open items. Closing this as a large issue like this is less helpful
