### ISSUE TITLE
Need a better indication that csv exporter expects a full file path

### ISSUE THREAD

**Issue by dj-dn** [brafdlog/caspion#423]
## System Info
        
         - Source Version: `SOURCE_COMMIT_SHORT`
         - OS: `browserjavascript`
         - OS Version: `5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) caspion/1.7.0 Chrome/98.0.4758.141 Electron/17.4.11 Safari/537.36`
         
         
<img width="509" alt="image" src="https://user-images.githubusercontent.com/104728153/209436767-e524ba07-e117-40d7-815c-109065f6a73b.png">

Where is this file? can I change permissions manually?

**Comment by dj-dn** [comment]
Hi, its actually working, it just expects a full path, maybe some remark can help there

**Comment by baruchiro** [comment]
Thank you, you're right.

Meanwhile, I think you can click to change the `transaction.csv` file, and it will open a File Choose Dialog where the current selected file is.

**Comment by ErezBiren** [comment]
I'm taking it. adding a file dialog to the new UI.

**Comment by ErezBiren** [comment]
Fixed.
#435
