### ISSUE TITLE
Enable/Disable toggle on Importer Form is not enabling the Save button

### ISSUE THREAD

**Issue by baruchiro** [brafdlog/caspion#424]
@ShiranAbir I think you create a regression bug here.

When I want to disable an importer temporarily, the **Save** button is disabled when I toggle the "enable/disable" toggle.

Look:

![2022-12-25 10-54-28](https://user-images.githubusercontent.com/17686879/209462214-9d898689-94d3-4fda-8072-7f656a54782d.gif)

_Originally posted by @baruchiro in https://github.com/brafdlog/caspion/issues/406#issuecomment-1364647405_

**Comment by ErezBiren** [comment]
Can I take this one as well?
