### ISSUE TITLE
Make the scraping timeout configurable and expose it in the ui of the settings

### ISSUE THREAD

**Issue by brafdlog** [brafdlog/caspion#430]
The scraping timeout is defined here:
https://github.com/brafdlog/caspion/blob/6a7719063327272f749eb2b2c8a281856c514ae0/src/backend/import/bankScraper.ts#L32

It is currently hard coded to 60 seconds.
We would like to make this timeout configurable by the user.

To do that we need to:

- [ ] Add it to the configuration (and set a default for old configurations)
- [ ] Expose in the settings UI the option to change it.

**Comment by ErezBiren** [comment]
Can I take it?

**Comment by brafdlog** [comment]
Of course 🙂
