### ISSUE TITLE
Add Bank Yahav

### ISSUE THREAD

**Issue by yairprog** [brafdlog/caspion#443]
Please add Bank Yahav to the available banks list.
![image](https://user-images.githubusercontent.com/27340287/212142813-211fa8f5-9d80-4bd5-8aa2-3ee8ea1d8749.png)

**Comment by ErezBiren** [comment]
I can take it.

**Comment by ErezBiren** [comment]
I see that Beyhad Bishvilha is also missing. should I do it in the same PR?

**Comment by brafdlog** [comment]
No need to separate PRs.

**Comment by ErezBiren** [comment]
Fixed in #444
