### ISSUE TITLE
Error: Hapoalim bank can't fetch data

### ISSUE THREAD

**Issue by yairprog** [brafdlog/caspion#447]
![image](https://user-images.githubusercontent.com/27340287/212558030-663f2cc0-fd58-49b2-acf4-3568cfd4c9f6.png)
![image](https://user-images.githubusercontent.com/27340287/212558046-c4f105a6-d751-4039-9667-48604df80c2f.png)

**Comment by brafdlog** [comment]
Seems like you need to change your password.
Please go to settings, abd ebable show browser.
Then run again and you will see if this is the problem
