### ISSUE TITLE
App not installed after "auto update"

### ISSUE THREAD

**Issue by baruchiro** [brafdlog/caspion#456]
I'm updating the app from inside the "Check for updates" button.

After the update is downloaded, I'm clicking on "exit and install", the installation starts, but after it finish I can't find the App anymore.

Windows 11.

**Comment by baruchiro** [comment]
> After updating the shortcut to the exe file is incorrect.
> 
> ## Log
> ```
> [2024-03-03 14:42:59.795] [debug] download range: bytes=73331520-73448975
> [2024-03-03 14:43:00.786] [info]  New version 1.24.0 has been downloaded to C:\Users\אהרן\AppData\Local\caspion-updater\pending\caspion.exe
> [2024-03-03 14:43:04.032] [info]  Install on explicit quitAndInstall
> [2024-03-03 14:43:04.033] [info]  Install: isSilent: false, isForceRunAfter: true
> [2024-03-03 14:43:05.122] [info]  Update installer has already been triggered. Quitting application.
> [2024-03-03 14:44:27.974] [info]  Welcome to caspion log
> [2024-03-03 14:44:27.980] [info]  Version: 1.24.0
> [2024-03-03 14:44:41.994] [info]  Welcome to caspion log
> [2024-03-03 14:44:42.002] [info]  Version: 1.24.0
>  
> ```
> 
> ## System Info
> * Source Version: `9dce6a8cbc9fd7f5c9fb48f487c14d521af8a1a5`
> * OS: `browserjavascript`
> * OS Version: `5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) caspion/1.24.0 Chrome/98.0.4758.141 Electron/17.4.11 Safari/537.36`
>
> _Copied from #543_

**Comment by grooverATR** [comment]
בתוך AppData\Local\caspion-updater\pending יש קובץ בשם caspion.exe וכשהפעלתי אותו חזר הקיצור דרך לשולחן העבודה
