### ISSUE TITLE
cal לא עובד

### ISSUE THREAD

**Issue by rgilat** [brafdlog/caspion#466]
## Details
        
        CAL שינו את הדף הראשי (כולל דף שמפנה לDASHBOARD חדש) והSCRAPER לא עובד
        ## System Info
        
         - Source Version: `af0b80331e39ae61eb1396117e590b5e63b41237`
         - OS: `browserjavascript`
         - OS Version: `5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) caspion/1.11.4 Chrome/98.0.4758.141 Electron/17.4.11 Safari/537.36`

**Comment by brafdlog** [comment]
מקור הבעיה הוא: https://github.com/eshaham/israeli-bank-scrapers/issues/763

**Comment by baruchiro** [comment]
> מקור הבעיה הוא: [eshaham/israeli-bank-scrapers#763](https://github.com/eshaham/israeli-bank-scrapers/issues/763)

Closing
