### ISSUE TITLE
dates are appearing one day behind in UTC instead of local timezone

### ISSUE THREAD

**Issue by sushi30** [brafdlog/caspion#483]
![image](https://github.com/brafdlog/caspion/assets/26347589/6005387e-a449-4f34-8a44-0e29cf326db6)

This creates records in my budgeting app with wrong dates. Willing to file a PR if anyone points me to the area where this is handled in the code.

**Comment by baruchiro** [comment]
To be honest, something in the timing is confusing me to the end.

I handled such a problem here https://github.com/eshaham/israeli-bank-scrapers/pull/783, but I'm still not sure how it should be and work, sorry.

You may need to fix it there, or somewhere here: https://github.com/brafdlog/caspion/blob/master/src/backend/transactions/transactions.ts

Thank you for your report! I hope you will find a solution.

We will need to see how it will not break everything.

You're welcome to join our [Discord server](https://discord.gg/EKPM4Ntc) if you want to discuss it.
