### ISSUE TITLE
Automatically create a PR for israeli-bank-scrapers upgrades

### ISSUE THREAD

**Issue by baruchiro** [brafdlog/caspion#536]
The project [israeli-bank-scrapers](https://github.com/eshaham/israeli-bank-scrapers) is the core library of our project, and since all the passwords the user enters in Caspion are passed into it, we're overviewing every upgrade of _israeli-bank-scrapers_ before upgrading.

When I see there is a new version of _israeli-bank-scrapers_, [I'm manually create a new PR](https://github.com/brafdlog/caspion/pulls?q=is%3Apr+Deps+israeli) (with upgrading in local env etc') with a description of the diff.

Requirements:
- A new Github Actions workflow
- Triggered every day or manually
- Upgrading the library with a `yarn` command
- Commiting the changes and open a PR
- Add the diff link and description of the versions.
- Make sure you're keeping this PR (and not open multiple PRs for each day or each version) while it's still open

**Comment by ronnahmias** [comment]
Hi, Can I take this issue? @baruchiro

**Comment by brafdlog** [comment]
Of course 🙂

**Comment by ronnahmias** [comment]
I have created workflow on my forked repo but maybe there is issue with running actions on fork repository.
Can you check please on the repo settings?

**Comment by ronnahmias** [comment]
And 1 more question - 
The diff link is something like this: https://github.com/eshaham/israeli-bank-scrapers/releases/tag/v4.2.2 ?
Of course, according to the version number
