### ISSUE TITLE
VISA CAL FAILURE - ver 1.25

### ISSUE THREAD

**Issue by agammyshhay** [brafdlog/caspion#549]
there is a repeated bug with VISA CAL :
" waiting for selector button.btn-close failed: timeout 30000ms exceeded"

thanks

i also reported here: https://github.com/eshaham/israeli-bank-scrapers/issues/841

**Comment by baruchiro** [comment]
Can you run it with "Open Browser" and check where it is getting stuck?

**Comment by agammyshhay** [comment]
hi

im sorry, its expired password, i should have check before.

thanks
