### ISSUE TITLE
MacOS v1.27.1 damaged

### ISSUE THREAD

**Issue by Nic3Guy** [brafdlog/caspion#565]
## Details
        
        After downloading the new .dmg file to update the caspion version to the latest
I get the error message that:
"caspion" is damaged and can't be opened..." 
        ## System Info
        
         - Source Version: `05ad9a0d38cd106fbaf8e265480033bf03aec0ee`
         - OS: `browserjavascript`
         - OS Version: `5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) caspion/1.26.1 Chrome/98.0.4758.141 Electron/17.4.11 Safari/537.36`
         
         
![Screenshot 2024-06-16 at 15 32 23](https://github.com/brafdlog/caspion/assets/17640648/895dc522-4eb3-4582-b965-f8d052006ff0)

**Comment by baruchiro** [comment]
Closing as a duplicate.

See [this message](https://github.com/brafdlog/caspion/issues/276#issuecomment-2101239892) and the next ones to solve it.
