### ISSUE TITLE
JS error on first run on a new M3 Mac

### ISSUE THREAD

**Issue by ikrascloudinary** [brafdlog/caspion#575]
<img width="371" alt="Screenshot 2024-07-31 at 10 59 00" src="https://github.com/user-attachments/assets/f182208e-d068-44f5-bd25-da35bb452273">

**Comment by baruchiro** [comment]
Check this please: https://github.com/brafdlog/caspion/issues/276#issuecomment-2101761170

**Comment by ikrascloudinary** [comment]
@baruchiro Thank you, this seems to be a different issue though.

Succeeded with installation and opening the app. The actual scraping throws this at start of the scraping process. Adjusted the title to reflect it

**Comment by deanko47** [comment]
set the chromium path. if you installed chromium as you should, type in terminal - which chromium - copy the output and place it in chromium path.

**Comment by ikrascloudinary** [comment]
Thank you @deanko47 - that was it. Missed that part in the installation 🙏
