### ISSUE TITLE
לא שולף נתונים ממקס

### ISSUE THREAD

**Issue by deanko47** [brafdlog/caspion#576]
## Details
        
הוא לא מצליח לשלוף נתונים כי ישנה הלוואה שנקראת ״הלוואה לרגע במולטי״ והtype שלה הוא generic שנראה שהוא מתקשה לזהות. מה אפשר לעשות עם זה? תודה

## System Info
        
- Source Version: `e1894f698a74c168c1979b04cff54bde2becdce8`
- OS: `browserjavascript`
- OS Version: `5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) caspion/1.27.2 Chrome/98.0.4758.141 Electron/17.4.11 Safari/537.36`

**Comment by baruchiro** [comment]
היי, תוכל לצרף את הטרנזקציה הרלוונטית?
