### ISSUE TITLE
Migrate into updated Vite structure

### ISSUE THREAD

**Issue by baruchiro** [brafdlog/caspion#578]
We have many deprecated dependencies and can't upgrade the `israeli-bank-scrapers` anymore because it upgraded its NodeJS version.

I migrated our code into a new updated template, with the latest technologies and a better project structure to support us in the future.

PR: #579 

Here is what is missing to finish the migration:

### Critical

- [x] CI: Need to migrate our CI pipeline (the validations on Pull Requests) into the new project
  - [x] Lint (if it pass)
  - [x] TypeScript check
  - [x] Build
- [x] CD: Need to migrate our publish procedure, and learn how the new project needs to be deployed (is it using `electron-builder` as we do, or something else?)
  - [x] Semantic-Release
  - [x] Create Release
  - [x] Upload Artifacts
- [x] Link to Discord (critical because I account this to be in contact with users and leave other things in "Not Critical")
- [x] Check YNAB
- [ ] Copy nuxt files and deployment

### Can be fixed after migration

- [ ] TypeScript issues
- [ ] Check for updates
- [ ] Readme file

---

Close #428

**Comment by brafdlog** [comment]
Fixed multiple Ynab issues. Ynab works now

**Comment by brafdlog** [comment]
Fixed discord link

**Comment by baruchiro** [comment]
Started to test the build pipeline, please check the artifacts on [v2.0.0 (draft)](https://github.com/brafdlog/caspion/releases/tag/untagged-8ffe4d18e95030b97394)

- [ ] Window
- [ ] Linux
- [ ] Mac (Intel)
- [ ] Mac (Apple)

**Comment by baruchiro** [comment]
![image](https://github.com/user-attachments/assets/4d7848e6-2757-4cb2-9cb4-76ab5479fece)

**Comment by baruchiro** [comment]
Now need to inject the Google client ID and client secret into the pipeline.

BTW, I failed to download the draft artifacts, don't know why, but in case you need another way, use this:

`gh release download v2.0.0-test.3 --pattern "caspion-2.0.0-test.3-arm64.dmg" --dir release`

**Comment by shaiu** [comment]
@baruchiro lint is working now so you can cross it out :)

**Comment by brafdlog** [comment]
@baruchiro  what solved this issue? I still see this issue when installing from the latest released version
> ![image](https://private-user-images.githubusercontent.com/17686879/363775565-4d7848e6-2757-4cb2-9cb4-76ab5479fece.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5MTE1MDQsIm5iZiI6MTcyNjkxMTIwNCwicGF0aCI6Ii8xNzY4Njg3OS8zNjM3NzU1NjUtNGQ3ODQ4ZTYtMjc1Ny00Y2IyLTljYjQtNzZhYjU0NzlmZWNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIxVDA5MzMyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyOTc2YTRlYzA3NWI5MzAxNmI4ZDBlN2I2NDk5Y2E5YWYzYmM3OGZkNTJkNDJkMjk5NWM2ODM5MGQxMDhkOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NlPMDdwWb6Tdz0ZTnsGE0R7GrS6SKy0pggc3v_DKWrY)
> 
> ### Update: problem solved

**Comment by shaiu** [comment]
@brafdlog I also see it. I'm debugging it now

**Comment by shaiu** [comment]
@brafdlog I found the issue.
Sending a PR

**Comment by shaiu** [comment]
@brafdlog @baruchiro https://github.com/brafdlog/caspion/pull/594

**Comment by brafdlog** [comment]
Nice, thanks @shaiu 
Merged the PR

**Comment by shaiu** [comment]
@brafdlog @baruchiro fixed tests: https://github.com/brafdlog/caspion/pull/595
