### ISSUE TITLE
Yahav broken

### ISSUE THREAD

**Issue by D3SL** [brafdlog/caspion#581]
```
Importer start

START_SCRAPING

INITIALIZING

INITIALIZING

LOGGING_IN

LOGIN_SUCCESS

TERMINATING

END_SCRAPING

GENERIC: Error: failed to find element matching selector ".dropdown-dir .selected-item-top
```

**Comment by baruchiro** [comment]
Maybe it related to https://github.com/eshaham/israeli-bank-scrapers/pull/882

**Comment by shaiu** [comment]
@D3SL can you please check if you still experience the problem with the latest release?

**Comment by D3SL** [comment]
Apologies I lost track of this. Yahav works, if I manually provide the missing chromium installation in post-rewrite versions, but ironically now Isracard fails to login.

**Comment by baruchiro** [comment]
Isracard worked for me today

**Comment by shaiu** [comment]
@baruchiro let's close this
