### ISSUE TITLE
Pressing "Turn on" doesn't do anything (Windows)

### ISSUE THREAD

**Issue by shaiu** [brafdlog/caspion#599]
**Describe the bug**
When pressing the "Turn on" button, nothing happens

**To Reproduce**

1. Go to main window
2. Click on 'הפעל'
3. Nothing happens

**Expected behavior**
The app should start scraping

**Additional context**
Windows env

**Comment by D3SL** [comment]
There's no chromium in caspion's folder, you'll have to provide it manually for the time being.

**Comment by baruchiro** [comment]
I think this issue was already solved by the last releases.
