### ISSUE TITLE
Add the option to export in CSV  

### ISSUE THREAD

**Issue by david1x** [brafdlog/caspion#631]
if someone is not a developer or not necessary want to use code to work with the data. 
I think it would be helpful if an option to work in excel direclty would be awesome. 
I know that there is an option to export to google sheet but to avoid login and keep working locally i think it would be a nice feature to export it to either CSV or XLSX

**Comment by brafdlog** [comment]
@david1x this is already supported
The excel exporter exports to CSV

<img width="353" alt="Screenshot 2024-12-11 at 22 55 27" src="https://github.com/user-attachments/assets/6fc2dfdb-1056-466f-a3c8-aeac54829444" />
